=== morlorc/WebServices/WebServices/WebContent/WEB-INF/bdd/associations.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="string_mail">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="string_SIREN">
		<xs:restriction base="xs:string">
			<xs:maxLength value = "9" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="string_mdp">
		<xs:restriction base="xs:string">
			<xs:minLength value = "8" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="associations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="association">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="string_SIREN" name="SIREN"/>
							<xs:element type="xs:string" name="nom_asso"/>
							<xs:element type="string_mail" name="mail_asso"/>
							<xs:element type="string_mdp" name="mdp_asso"/>
							<xs:element name="evenements">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="evenement" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:integer" name="id_event"/>
													<xs:element type="xs:string" name="nom_event"/>
													<xs:element type="xs:date" name="date_debut"/>
													<xs:element type="xs:date" name="date_fin"/>
													<xs:element type="xs:string" name="description_event"/>
													<xs:element name="candidatures">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="candidature" maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:string" name="nom_pers"/>
																			<xs:element type="xs:string" name="prenom_pers"/>
																			<xs:element type="xs:string" name="motivation"/>
																			<xs:element type="string_mail" name="mail_pers"/>
																			<xs:element type="xs:string" name="etat"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== morlorc/WebServices/WebServices/WebContent/WEB-INF/bdd/associations.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE xml>
<associations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="associations.xsd">
	<association>
		<SIREN>479606410</SIREN>
		<nom_asso>Promenades bucoliques SARL</nom_asso>
		<mail_asso>promenade@bucolique.fr</mail_asso>
		<mdp_asso>pKQvfXBEnP</mdp_asso>
		<evenements>
			<evenement>
				<id_event>05323</id_event>
				<nom_event>Balade party</nom_event>
				<date_debut>2018-03-30</date_debut>
				<date_fin>2018-03-31</date_fin>
				<description_event>Balade champêtre entre amis</description_event>
				<candidatures>
					<candidature>
						<nom_pers>Martin</nom_pers>
						<prenom_pers>Jean</prenom_pers>
						<motivation>Aime bien marcher moi</motivation>
						<mail_pers>jean.martin@gmail.com</mail_pers>
						<etat>En cours</etat>
					</candidature>
					<candidature>
						<nom_pers>Mamour</nom_pers>
						<prenom_pers>Jean-Michel</prenom_pers>
						<motivation>J’aime la nature</motivation>
						<mail_pers>jeanmichel.mamour@wanadoo.com</mail_pers>
						<etat>Accepté</etat>
					</candidature>
					<candidature>
						<nom_pers>Nerie</nom_pers>
						<prenom_pers>Mark</prenom_pers>
						<motivation>Cpaske c b1 lé chan</motivation>
						<mail_pers>thugdu92@yahool.fr</mail_pers>
						<etat>Refus</etat>
					</candidature>
				</candidatures>
			</evenement>
		</evenements>
	</association>
</associations>
