=== morlorc/WebServices/WebServices/WebContent/WEB-INF/bdd/personnes.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="personnes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="personne" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="nom_pers"/>
							<xs:element type="xs:string" name="prenom_pers"/>
							<xs:element type="xs:string" name="mail_pers"/>
							<xs:element type="xs:integer" name="age"/>
							<xs:element type="xs:string" name="mdp_pers"/>
							<xs:element name="candidatures">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="candidature" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="nom_asso"/>
													<xs:element type="xs:string" name="nom_event"/>
													<xs:element type="xs:date" name="date_debut"/>
													<xs:element type="xs:date" name="date_fin"/>
													<xs:element type="xs:string" name="etat"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== morlorc/WebServices/WebServices/WebContent/WEB-INF/bdd/personnes.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<personnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personnes.xsd">
    <personne>
        <nom_pers>Mamour</nom_pers>
        <prenom_pers>Jean-Michel</prenom_pers>
        <mail_pers>jeanmichel.mamour@wanadoo.com</mail_pers>
        <age>62</age>
        <mdp_pers>mamour2018</mdp_pers>
        <candidatures>
            <candidature>
                <nom_event>Balade party</nom_event>
                <date_debut>2018-03-30</date_debut>
                <date_fin>2018-03-31</date_fin>
                <etat>En cours</etat>
            </candidature>
        </candidatures>
    </personne>
    <personne>
        <nom_pers>Martin</nom_pers>
        <prenom_pers>Jean</prenom_pers>
        <mail_pers>jean.martin@gmail.com</mail_pers>
        <age>35</age>
        <mdp_pers>0452585erzer</mdp_pers>
        <candidatures>
            <candidature>
                <nom_event>Balade party</nom_event>
                <date_debut>2018-03-30</date_debut>
                <date_fin>2018-03-31</date_fin>
                <etat>Validé</etat>
            </candidature>
        </candidatures>
    </personne>
    <personne>
        <nom_pers>Nerie</nom_pers>
        <prenom_pers>Mark</prenom_pers>
        <mail_pers>thugdu92@yahoo.fr</mail_pers>
        <age>47</age>
        <mdp_pers>qwerty123r</mdp_pers>
        <candidatures>
            <candidature>
                <nom_event>Balade party</nom_event>
                <date_debut>2018-03-30</date_debut>
                <date_fin>2018-03-31</date_fin>
                <etat>Refusé</etat>
            </candidature>
        </candidatures>
    </personne>
    <personne>
        <nom_pers>pierre</nom_pers>
        <prenom_pers>abrand</prenom_pers>
        <mail_pers>p@a.fr</mail_pers>
        <age>21</age>
        <mdp_pers>mot de passe</mdp_pers>
        <candidatures></candidatures>
    </personne>
    <personne>
        <nom_pers>Petit</nom_pers>
        <prenom_pers>Ludovic</prenom_pers>
        <mail_pers>pt.ludo@gmail.com</mail_pers>
        <age>56</age>
        <mdp_pers>cmoiludo</mdp_pers>
        <candidatures></candidatures>
    </personne>
</personnes>
